name: opportunex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_plus: ^0.2.3
  image_picker: ^1.1.2
  intl: ^0.20.1
  screens: ^2.5.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logo2.png
    - lib/assets/images/profile.png
    - lib/assets/images/slider1.png
    - lib/assets/images/slider2.png
